var nodemailer = require('nodemailer');
var emailer=function (body,email) {
    var transport = nodemailer.createTransport({
        service: "gmail",
        auth: {
            user: "lecturerauth@gmail.com", //generated by Mailtrap
            pass: "bsef12m538" //generated by Mailtrap
        }
    });

    var mailOptions = {
        from: 'lecturerauth@gmail.com',
        to: email,
        subject: 'Account verification',
        text: body
    };
    transport.sendMail(mailOptions, function(error, info){
        if (error) {
            console.log(error);
        } else {
            console.log('Email sent: ' + info.response);
        }
    });
}
module.exports=emailer;