var nodemailer = require('nodemailer');
var config=require("../config/emailConfig.json");
var emailer=function (body,email) {
    var transport = nodemailer.createTransport({
        service: "gmail",
        auth: {
            user: config.authUser, //generated by Mailtrap
            pass: config.authPassword //generated by Mailtrap
        }
    });

    var mailOptions = {
        from: config.authUser,
        to: email,
        subject: 'Account verification',
        text: body
    };
    transport.sendMail(mailOptions, function(error, info){
        if (error) {
            console.log(error);
        } else {
            console.log('Email sent: ' + info.response);
        }
    });
}
module.exports=emailer;